# Generated by Django 4.2.1 on 2023-07-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_admin_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_table',
            new_name='admin_tables',
        ),
    ]
