# Generated by Django 4.2.1 on 2023-07-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_table_delete_admin_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table',
            new_name='table_admin',
        ),
    ]
