# Generated by Django 4.2.1 on 2023-07-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_admin_table_delete_table_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_table',
            new_name='admin_register',
        ),
    ]
